### ISSUE TITLE
About preprocessed data

### ISSUE THREAD

**Issue by penghao-wu** [dongkwonjin/Semantic-Line-MWCS#4]
Thank you for your great work! It seems that the preprocessed data downloaded from the provided link does not contain images?

**Comment by dongkwonjin** [comment]
Hi! Thank you for your interest. The data does not contain images. You can download the images at the following links:
https://github.com/dongkwonjin/Semantic-Line-DRM
https://kaizhao.net/nkl

Sorry for the late reply.
