### ISSUE TITLE
Questions about the checkpoint_final of S-Net

### ISSUE THREAD

**Issue by YiShiyi11** [dongkwonjin/Semantic-Line-MWCS#5]
Hello! 
When starting training S-Net, the following error occurs：
in load_model_for_train
    checkpoint = torch.load(cfg.dir['weight'] + 'checkpoint_final')
FileNotFoundError: [Errno 2] No such file or directory: '/MWCS/Modeling/S_Net/output_snet_SEL/train/weight/checkpoint_final'

Where can I get this weight file？
thanks！

**Comment by dongkwonjin** [comment]
Hello,

If you want to start training S-Net from scratch, you have to set "self.resume=True" in the options/config.py file.

Thank you for your attention :)

**Comment by YiShiyi11** [comment]
Another problem occurred： "dict_DB['val_result']" and "dict_DB['epoch']" don't exist  when I set "self.resume=True".

line 19, in __init__
    self.val_result = dict_DB['val_result']
KeyError: 'val_result'

**Comment by dongkwonjin** [comment]
Did you set self.run_mode = 'train' and self.resume = True in config.py?

Because "dict_DB['val_result']" and "dict_DB['epoch']" are initialized in line 91-106 in libs/prepare.py.

Thank you.
